apiVersion: v1
kind: ConfigMap
metadata:
  name: user
data:
  ENVIRONMENT: "dev"
  AWS_REGION: "us-east-1"
  DB_HOST: "ecommerce-dev-rds-postgres"
  DB_PORT: "5432"
  DB_NAME: "ecommercedb"
  # DB_USER: "postgres"       # Created as secrets by eso operator
  # DB_PASSWORD: ""           # Created as secrets by eso operator
