apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app.kubernetes.io/name: user
    app.kubernetes.io/owner: ecommerce 
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8003
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: user
    app.kubernetes.io/owner: ecommerce
