apiVersion: v1
kind: ServiceAccount
metadata:
  name: cart
  namespace: ecommerce-dev
  labels:
    app.kubernetes.io/name: cart
    app.kubernetes.io/owner: ecommerce
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/ecommerce-dev-cart-role
automountServiceAccountToken: true   # Default is "true"
