apiVersion: v1
kind: Service
metadata:
  name: cart-service
  labels:
    app.kubernetes.io/name: cart
    app.kubernetes.io/owner: ecommerce 
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8002
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: cart
    app.kubernetes.io/owner: ecommerce
