apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    app.kubernetes.io/name: product
    app.kubernetes.io/owner: ecommerce 
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8001
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: product
    app.kubernetes.io/owner: ecommerce
