apiVersion: v1
kind: ServiceAccount
metadata:
  name: product
  # namespace: ecommerce-dev
  labels:
    app.kubernetes.io/name: product
    app.kubernetes.io/owner: ecommerce
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/ecommerce-dev-product-role
automountServiceAccountToken: true   # Default is "true"
